# Site settings
title:       "RUniteCS"
header_title: "RUniteCS"
email:       rutgersusacs@gmail.com
webmaster:      Alexander Goodkind
description: "A volunteer outreach program to spark interest in computer science in middle school students"
baseurl:     "" # no trailing slash !
url:         "https://runitecs.org"
date_format: "%-d.%m.%Y"

# Google services
google_analytics: "UA-124239918-2"
google_verification: ""

# Facebook
facebook_app_id: ""

# Optional features
animated:             false
show_related_posts:   false
show_post_footer:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 
# https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder
google_api_key: AIzaSyA07liNlwBQDLqiOmVz5uvKxVxSk34Q4ko

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username: rutgers_usacs
google_plus_id:
linkedin_username:
facebook_username: 
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

permalink:    "/:title/"
paginate:     15
sass:
  compressed: true

# Gems
plugins: [jekyll-paginate]

defaults:
  - scope:
      path: "docs/photos"
    values:
      photo: true
